services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
      - "8443:443"
    volumes:
      - ./config/php.ini-development:/usr/local/etc/php/php.ini
      - ./etc/ssl-certs:/etc/ssl-certs
      - ./app:/var/www
    environment:
      - APP_ENV=dev

  mysql:
    ports:
      - "3310:3306"
    env_file:
      - ./app/.env.local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8899:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
