services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9010:9000"
    volumes:
      - ./config/php.ini-development:/usr/local/etc/php/php.ini
      - ./app:/var/www
    environment:
      - APP_ENV=dev

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./app:/var/www
    depends_on:
      - app

  mysql:
    ports:
      - "3310:3306"
    env_file:
      - ./app/.env.local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8899:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"