services:
  app:
    build:
      context: .
      dockerfile: app/docker/Dockerfile.dev
    volumes:
      - ./app:/var/www
      - ./app/docker/php-fpm/dev.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./app/docker/php/dev.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - APP_ENV=dev
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/public:ro
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./app/.env.local
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8899:80"
    env_file:
      - ./app/.env.local
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - PMA_UPLOAD_LIMIT=128M
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped

volumes:
  mysql-data: