services:
  app:
    build:
      context: .
      dockerfile: app/docker/Dockerfile
    volumes:
      - ./app:/var/www
      - ./app/docker/php-fpm.d/www.prod.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./app/docker/php/php.prod.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - APP_ENV=prod
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ./app/public:/var/www/public:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - app/.env.prod
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped

volumes:
  mysql-data: