FROM php:8.3-apache

# User and group configuration
ARG USER_ID
ARG GROUP_ID
RUN groupadd -g $GROUP_ID appuser \
    && useradd -m -u $USER_ID -g appuser appuser

# Global configuration/installation
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y zlib1g-dev g++ git libicu-dev zip libzip-dev netcat-openbsd \
    && pecl install apcu \
    && docker-php-ext-install intl opcache pdo pdo_mysql \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Apache configuration
RUN a2enmod rewrite && a2enmod ssl && a2enmod socache_shmcb

# Composer installation
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Symfony CLI installation
RUN curl https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

# Dart Sass installation
RUN curl -SL https://github.com/sass/dart-sass/releases/download/1.71.1/dart-sass-1.71.1-linux-x64.tar.gz -o dart-sass.tar.gz \
    && tar -xzf dart-sass.tar.gz -C /usr/local/bin --strip-components=1 \
    && rm dart-sass.tar.gz

# Working directory
WORKDIR /var/www

# Copy and give permissions to execute the scripts
COPY scripts/dev/*.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/*.sh

# Change to non-root user (appuser)
USER appuser

# Execute the script build-docker.sh
CMD ["/usr/local/bin/build-docker.sh"]
