framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: 'http://localhost:8080'

when@prod:
    framework:
        router:
            default_uri: 'https://gaelpaquien.com'
            strict_requirements: null
